from pathlib import Path
import base64
import subprocess

from generer_support import CSS, esc, shell

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'outputs'
subprocess.run(['dot','-Tsvg',str(Path(__file__).with_name('architecture.dot')),'-o',str(OUT/'architecture-uml.svg')],check=True)
diagram=base64.b64encode((OUT/'architecture-uml.svg').read_bytes()).decode()
criteria=[
('Architecture et rôles des composants','Vérifié','Schéma UML de composants simplifié ci-dessus, modules métier séparés ; rapport et README explicitent les responsabilités.'),
('Choix du modèle et adaptation métier','Livré, comparaison à compléter','Mistral imposé dans la mission ; mistral-embed pour la recherche ; Small historiquement et Ministral 8B pour la démo actuelle ; prompt Puls-Events. Pas de benchmark comparatif ni entraînement.'),
('Descriptions transformées en vecteurs','Vérifié','14 903 vecteurs de 1 024 dimensions ; 7 586 UID représentés, modèle mistral-embed tracé dans le manifeste.'),
('Chaîne LangChain et FAISS','Livré','Documents, splitters, retriever, prompt et clients Mistral ; l’orchestration est écrite dans le projet.'),
('Pertinence des réponses annotées','Preuve initiale','4 cas locaux avec règles permissives ; 3 cas RAGAS, correction moyenne 0,683. Ce n’est pas une validation générale.'),
('Tests des étapes du pipeline','Vérifié aujourd’hui','76 tests réussis ; services externes simulés dans la suite. Ingestion, chunks, index, RAG, API, démo et métriques couverts.'),
('Tests relançables et résultats lisibles','Livré','python -m pytest -q ; scripts d’évaluation ; rapports JSON locaux. CI/CD proposée, pas implémentée.'),
('Indicateurs et analyse des erreurs','Livré, à enrichir','Règles de titres, refus, exact match et similarité lexicale ; 4 métriques RAGAS. Petit jeu, détails fragiles et absence de seuil reconnus.'),
('Dépôt lisible et reproductible','Livré','scripts/, src/, tests/, seed-data/, README, versions directes et Docker. Les supports de soutenance sont versionnés ; README constitue aussi un rapport.'),
('Références humaines et comparaison automatisée','Livré','Deux CSV annotés ; evaluate_rag.py et evaluate_ragas.py. Le second est le vrai calcul RAGAS ; l’option --ragas du premier ne le remplace pas.'),
('API /ask et /rebuild','Partiellement vérifié aujourd’hui','Serveur lancé, Swagger disponible ; deux scénarios /ask réussis avec Ministral 8B. /rebuild est livré mais non relancé pendant la préparation.'),
('Validation et gestion des erreurs','Livré, durcissement à prévoir','Pydantic, rejet des questions vides, erreurs HTTP ; erreurs fournisseur contrôlées en 503/502 sans détails internes. La pagination concerne la collecte, pas la réponse top-k.'),
('Lancement local','Vérifié','Image Docker existante démarrée via Compose. Aucun nouveau build complet affirmé ; dépendance Mistral distante.'),
('Qualité et fraîcheur des données','À compléter pour aujourd’hui','Nettoyage et déduplication livrés. Seed de juillet 2026 : certains événements ont plus d’un an au 1er octobre ; horizon futur et actualisation à ajouter.'),
('Contrat et exemples API','Vérifié','Swagger /docs, schéma OpenAPI, curl et scripts Python. GET /health existe ; /metadata cité comme exemple dans la fiche n’est pas livré ni nécessaire aux routes explicites du brief.'),
('JSON exploitable et cas limites','Livré','question, answer, sources et retrieved_chunk_count ; refus Lyon enregistré. Pas de filtre de ville bloquant, ni seuil de pertinence.'),
('Démo fluide et explication aux métiers','Direct vérifié aujourd’hui','Démonstrateur local avec direct et enregistrement explicitement séparés ; guide oral, exemples et glossaire. Le secours ne remplace pas l’exigence live.'),
('Sécurité avant exposition publique','À compléter','Clé dans l’environnement, .env ignoré ; jeton /rebuild optionnel. Authentification globale, limite de débit et bascule atomique à prévoir ; erreurs fournisseur déjà filtrées.'),
]
rows=''.join(f'<tr><td>{esc(c)}</td><td><strong>{esc(s)}</strong></td><td>{esc(n)}</td></tr>' for c,s,n in criteria)
body=f'''<main><p class="eyebrow">Complément de préparation · 1er octobre 2026</p><h1>Architecture et autoévaluation</h1><p><a href="guide-soutenance-openagenda-rag.html#conformite">Retour au guide</a> · <a href="rapport-technique-openagenda-rag.pdf">Rapport technique existant</a></p><p>Cette annexe explique les composants effectivement livrés et reprend, en les reformulant, les critères de la fiche d’autoévaluation liée à la mission. Les états indiquent les preuves observées ; aucun critère incomplet n’est présenté comme validé.</p><h2>Schéma UML de composants simplifié</h2><img src="data:image/svg+xml;base64,{diagram}" alt="Schéma des dépendances : client HTTP vers FastAPI, service, RAG, FAISS et Mistral ; préparation OpenAgenda vers Parquet puis indexation." style="width:100%;height:auto"><p>Les flèches pointent vers le composant appelé ou l’artefact produit. Les modules Python regroupent des fonctions : ce diagramme montre leurs responsabilités et dépendances, pas une hiérarchie de classes inexistante.</p><div class="callout"><strong>Comment lire ce schéma</strong><p>Le client appelle FastAPI. L’API délègue au service. Pour une question, le service utilise le moteur RAG et l’index local ; Mistral reste externe pour l’embedding de question et la réponse. Pour reconstruire, le service relit le Parquet et utilise l’indexation, qui appelle Mistral pour les vecteurs. La collecte est une étape préalable distincte.</p></div><h2>Ce qui est vérifié, livré ou reste ouvert</h2><div class="table-wrap"><table><thead><tr><th>Critère reformulé</th><th>État</th><th>Preuve et limite</th></tr></thead><tbody>{rows}</tbody></table></div><h2>Les points à garder en tête à 14 h</h2><ol><li>Le corpus figé doit être actualisé pour remplir durablement le besoin de sorties à venir et de données de moins d’un an.</li><li>La démo fonctionne avec Ministral 8B après une limite sur Small ; annoncer le changement et réévaluer la qualité.</li><li>Les résultats RAGAS sont historiques et portent sur trois cas ; la correction 0,683 montre une marge d’amélioration.</li><li>Les 76 tests valident les comportements du code avec des doublures, sans prouver la disponibilité du fournisseur.</li></ol><p class="muted">Sources : code du dépôt, manifestes, corpus, sorties historiques et vérifications du 1er octobre ; fiche d’autoévaluation officielle liée au document de mission, consultée aujourd’hui.</p></main>'''
css='''main{max-width:1300px;margin:auto;padding:40px 35px}h1{font-size:42px}h2{font-size:28px;margin-top:35px}table{width:100%;border-collapse:collapse}th,td{text-align:left;vertical-align:top;padding:14px 12px;border-bottom:1px solid var(--line);font-size:15px}th{background:var(--pale)}td:nth-child(1){width:22%}td:nth-child(2){width:20%}.table-wrap{overflow:auto}@media print{@page{size:A4 landscape;margin:12mm}main{padding:0}h1{font-size:25px}h2{font-size:21px}table td,table th{font-size:11px}tr{break-inside:avoid}img{max-height:150mm}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}'''
(OUT/'architecture-autoevaluation-soutenance.html').write_text(shell('Architecture et autoévaluation — POC Puls-Events',body,css))
print('Annexe architecture et autoévaluation générée.')
